### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by roncemer** [leei/node-dbstore#1]
Does this thing really work, or not?

I'm on Ubuntu 15.04 64-bit.

I run: npm install dbstore

I get these errors:

make[1]: Entering directory '/var/lib/lxc/obdev/rootfs/home/rcemer/obm/php/node_projects/node_modules/dbstore/build'
  CXX(target) Release/obj.target/addon/src/addon.o
  CXX(target) Release/obj.target/addon/src/dbstore.o
../src/dbstore.cc: In function ‘void dbt_set(DBT_, void_, u_int32_t, u_int32_t)’:
../src/dbstore.cc:67:30: error: ‘memset’ was not declared in this scope
   memset(dbt, 0, sizeof(_dbt));
                              ^
../src/dbstore.cc: In static member function ‘static v8::Handlev8::Value DbStore::Open(const v8::Arguments&)’:
../src/dbstore.cc:205:33: error: ‘strdup’ was not declared in this scope
   baton->str_arg = strdup(_fname);
                                 ^
../src/dbstore.cc: In function ‘void PutWork(uv_work_t_)’:
../src/dbstore.cc:266:58: error: ‘strlen’ was not declared in this scope
   dbt_set(&key_dbt, baton->str_arg, strlen(baton->str_arg));
                                                          ^
../src/dbstore.cc:267:8: warning: unused variable ‘data_dbt’ [-Wunused-variable]
   DBT &data_dbt = baton->inbuf;
        ^
../src/dbstore.cc: In static member function ‘static v8::Handlev8::Value DbStore::Put(const v8::Arguments&)’:
../src/dbstore.cc:318:31: error: ‘strdup’ was not declared in this scope
   baton->str_arg = strdup(_key);
                               ^
../src/dbstore.cc: In function ‘void GetWork(uv_work_t_)’:
../src/dbstore.cc:339:58: error: ‘strlen’ was not declared in this scope
   dbt_set(&key_dbt, baton->str_arg, strlen(baton->str_arg));
                                                          ^
../src/dbstore.cc: In static member function ‘static v8::Handlev8::Value DbStore::Get(const v8::Arguments&)’:
../src/dbstore.cc:396:31: error: ‘strdup’ was not declared in this scope
   baton->str_arg = strdup(_key);
                               ^
../src/dbstore.cc: In function ‘void DelWork(uv_work_t_)’:
../src/dbstore.cc:411:58: error: ‘strlen’ was not declared in this scope
   dbt_set(&key_dbt, baton->str_arg, strlen(baton->str_arg));
                                                          ^
../src/dbstore.cc: In static member function ‘static v8::Handlev8::Value DbStore::Del(const v8::Arguments&)’:
../src/dbstore.cc:441:31: error: ‘strdup’ was not declared in this scope
   baton->str_arg = strdup(_key);

**Comment by miopa** [comment]
Not building also on CentOs 6.5 32bit

```
make[1]: Entering directory `/var/www/node.js/node_modules/dbstore/build'
  CXX(target) Release/obj.target/addon/src/addon.o
In file included from ../src/addon.cc:4:
../src/dbstore.h:8: error: expected class-name before ‘{’ token
../src/dbstore.h:29: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:29: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:29: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:31: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:31: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:31: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:32: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:32: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:32: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:34: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:34: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:34: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:35: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:35: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:35: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:36: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:36: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:36: error: expected ‘;’ before ‘&’ token
../src/dbstore.h:38: error: expected unqualified-id before ‘&’ token
../src/dbstore.h:38: error: expected ‘)’ before ‘&’ token
../src/dbstore.h:38: error: expected ‘;’ before ‘&’ token
In file included from ../src/addon.cc:5:
../src/dbenv.h:6: error: expected class-name before ‘{’ token
../src/dbenv.h:14: error: expected unqualified-id before ‘&’ token
../src/dbenv.h:14: error: expected ‘)’ before ‘&’ token
../src/dbenv.h:14: error: expected ‘;’ before ‘&’ token
../src/dbenv.h:15: error: expected unqualified-id before ‘&’ token
../src/dbenv.h:15: error: expected ‘)’ before ‘&’ token
../src/dbenv.h:15: error: expected ‘;’ before ‘&’ token
make[1]: *** [Release/obj.target/addon/src/addon.o] Error 1
make[1]: Leaving directory `/var/www/node.js/node_modules/dbstore/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-431.1.2.0.1.el6.i686
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /var/www/node.js/node_modules/dbstore
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
make: *** [all] Error 1
```
